---
- name: "Provision Machine"
  hosts: groupB
  serial: 1

  tasks:
    
    - name: showmsg
      debug:
        msg: "{{item}}"
      with_items:
        - "{{ansible_distribution}}" 
        - "{{ansible_user}}"
        
    - name: Check if Hypervisor
      shell: dmesg | grep "Hypervisor"
      become: true
      register: isvm
      failed_when: isvm.rc != 0 and isvm.rc != 1
      
    - include: os/{{ansible_distribution|lower}}.yml

    - name: Add user to docker group
      command: "{{item}}"
      with_items:
        - 'usermod -aG docker {{ansible_user}}'
        - 'systemctl enable docker'
      become: true

    - name: Download rustup-init
      get_url:
        url: 'https://sh.rustup.rs'
        dest: '/tmp/rustup-init.sh'
        mode: '0644'

    - name: Install rust
      shell: |
        if [ ! -d "/home/{{ansible_user}}/.cargo" ]; then
          bash /tmp/rustup-init.sh -y
        else
          echo 'rust already exist'
        fi

    - name: Clone oh-my-zsh github repo
      git:
        repo: 'http://github.com/robbyrussell/oh-my-zsh.git'
        dest: '/home/{{ansible_user}}/.oh-my-zsh'
        update: no

    # Using official .zshrc for now. later may use own zshrc
    - name: Install oh-my-zsh
      copy:
        src: /home/{{ansible_user}}/.oh-my-zsh/templates/zshrc.zsh-template
        dest: /home/{{ansible_user}}/.zshrc
        remote_src: yes

    # Install zsh-nvm (Plugin for nvm in zsh)
    - name: Install zsh-nvm
      git:
        repo: 'https://github.com/lukechilds/zsh-nvm.git'
        dest: '/home/{{ansible_user}}/.oh-my-zsh/custom/plugins/zsh-nvm'

    # chsh for user
    - name: Chsh to zsh
      command: 'chsh -s /bin/zsh {{ansible_user}}'
      become: true

    # Clone dotfiles git repo
    - name: Clone dot files git repo
      git:
        repo: 'https://github.com/clive2000/dotfiles.git'
        dest: '/tmp/dotfiles'

    - name: install dotfiles
      command: 'bash install.sh'
      args:
        chdir: '/tmp/dotfiles'
